// Builds each page in PAGES into examples/<page>/index.html, single self-
// contained file (CSS/JS inlined) so the Python backend's _file_handler can
// keep serving them verbatim.

import { build } from "vite";
import { viteSingleFile } from "vite-plugin-singlefile";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { themeInitPlugin } from "./theme-init-plugin.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));

const PAGES = ["landing", "login", "chat_client"];

const BANNER = (page) =>
  `<!-- AUTO-GENERATED by web/scripts/build.mjs from web/src/${page}/. Do not edit directly; edit the source and re-run \`npm run build\`. -->\n`;

async function buildPage(page) {
  const root = resolve(__dirname, "../src", page);
  const outDir = resolve(__dirname, "../../examples", page);
  await build({
    root,
    plugins: [themeInitPlugin(), viteSingleFile()],
    logLevel: "info",
    build: {
      outDir,
      emptyOutDir: true,
      cssCodeSplit: false,
      assetsInlineLimit: 100_000_000,
      rollupOptions: {
        output: {
          inlineDynamicImports: true,
        },
      },
    },
  });
  // Prepend the AUTO-GENERATED banner so anyone opening the produced file
  // sees the warning before the doctype.
  const out = resolve(outDir, "index.html");
  const html = readFileSync(out, "utf8");
  if (!html.startsWith("<!-- AUTO-GENERATED")) {
    writeFileSync(out, BANNER(page) + html);
  }
  console.log(`[build] ${page} -> ${out}`);
}

let failed = false;
for (const page of PAGES) {
  try {
    await buildPage(page);
  } catch (err) {
    failed = true;
    console.error(`[build] ${page} failed:`, err);
  }
}
process.exit(failed ? 1 : 0);
